#!/bin/bash
root="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." >/dev/null 2>&1 && pwd )"
cd "$root"
source "$root/script/helpers/utils.sh"
load_config

release_arg=
if [ "$configuration" = "release" ]; then
    release_arg="--release"
fi

info "Building ana-os/start for $kernel_target..."
cargo bootimage

# cargo +nightly build --target $kernel_target_path $release_arg

# cd "$root/crates/start"
# metadata=$(cargo metadata --format-version 1)
# root_id=$(echo "$metadata" | jq -r '.resolve.root')
# bootloader_id=$(echo "$metadata" | jq -r ".resolve.nodes[] | select(.id == \"$root_id\") | .deps[] | select(.name == \"bootloader\") | .pkg")
# bootloader_manifest_path=$(echo "$metadata" | jq -r ".packages[] | select(.id == \"$bootloader_id\") | .manifest_path")
# bootloader_dir=$(dirname "$bootloader_manifest_path")

# cd "$bootloader_dir"
# cargo builder \
#     --target-dir "$root/target" \
#     --out-dir "$root/target/$kernel_target/$configuration/" \
#     --kernel-manifest "$root/crates/start/Cargo.toml" \
#     --kernel-binary "$root/target/$kernel_target/$configuration/start"