#!/usr/bin/env bash
root="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." >/dev/null 2>&1 && pwd )"
cd "$root"

if [ ! -e "$root/.qemu.sock" ]; then
    echo "QEMU is not running, launch it with 'script/qemu'" 1>&2
    exit 1
fi

echo "$@" | nc -N -U "$root/.qemu.sock"