#!/usr/bin/env bash
root="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." >/dev/null 2>&1 && pwd )"
cd "$root"

kernel_bin="$1"

bootloader_id=$(cargo metadata --format-version 1 | jq -r '.resolve.nodes[] | select(.id | startswith("ana-kernel")) | .deps[] | select (.name == "bootloader") | .pkg')
manifest_path=$(cargo metadata --format-version 1 | jq -r ".packages[] | select(.id == \"$bootloader_id\") | .manifest_path")
manifest_dir=$(dirname $manifest_path)

cd "$manifest_dir"

cargo builder --kernel-manifest "$root/ana-kernel/Cargo.toml" --kernel-binary "$kernel_bin" --out-dir "$(dirname $kernel_bin)" --target-dir "$root/target"